### PR TITLE
Set UTF-8 locale

### LINKED ISSUE #18: Set up UTF8 locale

### PR DESCRIPTION
**Pull request by FloopCZ**
Closes #18

### CODE REVIEW

**Comment by FloopCZ** [comment]
Hmm, Python 3 locale madness. The position should not matter, can you please try to run bash in your container, execute `export LC_ALL=en_us.UTF-8` and then your script?

**Comment by petrbel** [comment]
I agree with @blazekadam, I think this should be set as soon as possible. I had many troubles with locales on school cluster.

**Comment by FloopCZ** [comment]
I can surely move it, but I don't think it will help. I would like to know what is the real cause of the issue. @blazekadam please try the aforementioned procedure?

**Comment by blazekadam** [comment]
I think that my issue was related to CI engine. Your update should do it.

**Pull request merged**
